services:
  mysql:
    image: mysql:8.0
    container_name: sghss-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sghss
      MYSQL_USER: everd
      MYSQL_PASSWORD: 2014
    ports:
      - "3306:3306"
    volumes:
      - mysql_sghss_data:/var/lib/mysql

volumes:
  mysql_sghss_data: